spring:
 profiles:
  active: dev
---
#??
server:
 port: 80 
spring:
 profiles: dev
---
#??
server:
 port: 81
spring:
 profiles: pro
---
#??
server:
 port: 82
spring:
 profiles: test
---
spring:
 config:
  activate:
   on-profile: dev